name: parallel-jobs

on:
  push:
  workflow_dispatch:

jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - name: Job One
        run: echo "Job 1 lancé par ${{ github.actor }} sur ${{ github.ref }}"

  job-two:
    runs-on: ubuntu-latest
    steps:
      - name: Job Two
        run: echo "Job 2 lancé par ${{ github.actor }} sur ${{ github.sha }}"
